import { Navigation } from '@/components/Navigation'
import ScrollTopButton from '@/components/ScrollTopButton'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Pedro.dev - Portfolio',
  description: 'Generated by create next app',
}

export default function LocaleLayout({
  children,
  params: {locale}
}: {
  children: React.ReactNode;
  params: {locale: string};
}) {
  return (
    <html lang={locale}>
      <body className={inter.className + " xl:max-w-[1280px] lg:mx-auto overflow-x-hidden"}>
        <Navigation />
        {children}
        <ScrollTopButton />
        </body>
    </html>
  );
}