import { Navigation } from '@/components/Navigation'
import ScrollTopButton from '@/components/ScrollTopButton'
import type { Metadata } from 'next'
import { NextIntlClientProvider, useMessages } from 'next-intl'
import { Inter } from 'next/font/google'
import '../globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Pedro.dev - Portfolio',
  description: 'Generated by create next app',
}

export default function LocaleLayout({
  children,
  params: {locale}
}: {
  children: React.ReactNode;
  params: {locale: string};
}) {
  const messages = useMessages();

  return (
    <html lang={locale}>
      <body className={inter.className + " xl:max-w-[1280px] lg:mx-auto overflow-x-hidden"}>
        <NextIntlClientProvider locale={locale} messages={messages}>
        <Navigation />
          {children}
        </NextIntlClientProvider>
        <ScrollTopButton />
        </body>
    </html>
  );
}